//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by xgraph_resources.rc
//
#define IDD_CHARTPROPERTIES             5000
#define IDAPPLY                         5002
#define IDB_BS0                         5003
#define IDD_CURVE                       5004
#define IDB_BS1                         5005
#define IDB_BS2                         5006
#define IDD_AXIS                        5007
#define IDB_BS3                         5008
#define IDB_BS4                         5009
#define IDB_BS5                         5010
#define IDD_CHART                       5011
#define IDD_LABELDLG                    5012
#define IDD_AVG                         5013
#define IDD_TRENDDLG                    5014
#define IDC_BUTTON1                     6001
#define IDC_BUTTON2                     6002
#define IDC_SPINLINESIZE                6006
#define IDC_COLOR                       6007
#define IDC_CBLINESTYLE                 6008
#define IDC_CBVISIBLE                   6009
#define IDC_NAME                        6010
#define IDC_CBFILL                      6011
#define IDC_CBTRANSPARENT               6012
#define IDC_MAX                         6013
#define IDC_CBGRID                      6014
#define IDC_CBTIMEAXIS                  6015
#define IDC_PRECISION                   6016
#define IDC_SPINPRECISION               6017
#define IDC_ARCSIZE                     6018
#define IDC_SPINARCSIZE                 6019
#define IDC_TICKSIZE                    6020
#define IDC_SPINTICKSIZE                6021
#define IDC_MARKERSIZE                  6022
#define IDC_SPINMARKERSIZE              6023
#define IDC_STEP                        6024
#define IDC_STARTDATE                   6025
#define IDC_STARTTIME                   6026
#define IDC_BSSTYLE1                    6027
#define IDC_BSSTYLE2                    6028
#define IDC_ENDDATE                     6029
#define IDC_ENDTIME                     6030
#define IDC_BSSTYLE5                    6031
#define IDC_BSSTYLE6                    6032
#define IDC_GRIDCOLOR                   6033
#define IDC_CBTYPE                      6034
#define IDC_LINESIZE                    6035
#define IDC_CBMARKER                    6038
#define IDC_CBAUTOSCALE                 6039
#define IDC_MIN                         6040
#define IDC_BSSTYLE3                    6042
#define IDC_BSSTYLE4                    6043
#define IDC_BSSTYLE0                    6045
#define IDC_DATETIMEFORMAT              6046
#define IDC_BKCOLOR                     6047
#define IDC_CHARTCOLOR                  6048
#define IDC_INNERCOLOR                  6049
#define IDC_CBSHOWLEGEND                6050
#define IDC_MARGINS                     6051
#define IDC_CBDOUBLEBUFFER              6052
#define IDC_BORDER                      6054
#define IDC_CBXAXIS                     6055
#define IDC_CBALIGNMENT                 6056
#define IDC_CBCURVE                     6057
#define IDC_CBSHOWMARKERS               6058
#define IDC_MARKERTYPE_SYMBOL           6059
#define IDC_CBO_MARKER_SYMBOLS          6060
#define IDC_MARKERTYPE_NUMBER           6062
#define IDC_WSIZE                       6063
#define IDC_SPINWSIZE                   6064
#define IDC_MAVG                        6065
#define IDC_LINTREND                    6066
#define IDC_CUBTREND                    6067
#define IDC_FONT                        6068
#define IDC_SPIN1                       6069
#define IDC_CBYAXIS                     6070
#define IDC_CURVE                       6071
#define IDC_CBGRIDTYPE                  6072
#define IDC_TAB                         6073
#define IDC_SPINTOL                     6074
#define IDC_TOLERANCE                   6075
#define IDC_CBSNAP                      6076
#define IDC_PLACEMENT                   6077
#define IDC_TRANSPARENT                 6078
#define IDC_EDIT1                       6079
#define IDC_POLYTREND                   6080
#define IDC_TIMESTEP                    6081
#define IDC_EDIT2                       6082
#define IDC_CBTIMESTEPTYPE              6083
#define IDC_SPIN2                       6084
#define IDC_CBFILLCURVE                 6086
#define IDC_BSSTYLE0_BITMAP             6087
#define IDC_BSSTYLE1_BITMAP             6088
#define IDC_BSSTYLE2_BITMAP             6089
#define IDC_BSSTYLE3_BITMAP             6090
#define IDC_BSSTYLE4_BITMAP             6091
#define IDC_BSSTYLE5_BITMAP             6092
#define IDC_BSSTYLE0_BITMAP6            6093
#define IDC_BSSTYLE6_BITMAP             6093
#define IDM_SELECT                      40000
#define IDM_INSERTLABEL                 40001
#define IDM_ZOOM                        40002
#define IDM_RESET                       40003
#define IDM_PAN                         40004
#define IDM_PROPERTIES                  40005
#define IDM_LABELDOPROP                 40006
#define IDM_PRINT                       40007
#define IDM_MAGNIFIER                   40008
#define IDM_LINEARTREND                 40009
#define IDM_CUBICTREND                  40010
#define IDM_CURSOR                      40011
#define IDM_PARENTCALLBACK              40012
#define IDM_ZOOM_BACK                   40013
#define IDM_EDITCURVE                   40014
#define IDM_MEASURE                     40015
#define IDM_DELETE_MEASURES             40016

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        40016
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         6094
#define _APS_NEXT_SYMED_VALUE           40113
#endif
#endif
